name: Theme deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Initialize project
        run: make init

      - name: Build project
        run: make build

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          shopify theme push \
            --json \
            --theme cookiediet_au \
            --store cookieau-test \
            --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}