name: Deploy

on: [ "workflow_dispatch" ]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Branch: ${{ env.BRANCH_NAME }}"