name: Deploy

on: [ "workflow_dispatch" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Initialize project
        run: make init

      - name: Build project
        run: make build

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli

      - name: Upload theme
        run: |
          shopify theme push \
            --json \
            --unpublished \
            --store ${{ vars.SHOPIFY_FLAG_STORE }} \
            --theme cookiediet/${{ github.ref_name }} \
            --password ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
